//! Plan-04 §12's cross-plugin contract — the binder over plan-03's own output.
//!
//! No `ra_ap`, no engine, no slow path: the input is a checked-in dump of what
//! `reachgraph-lang-rust` emits for its `fx-impl` fixture, regenerated only by
//! `cargo xtask golden-symbols --bless`. It fails if that plugin changes the
//! `raw_kind` grammar this crate parses, the `container` relation it walks, the
//! `is_test` flag it sets, or the path spelling it uses.
//!
//! # Two guards, without which this is self-consistent rather than contractual
//!
//! First, the golden file is regenerated by a deliberate command and never by a
//! test run, so a change cannot update both sides at once. Second, the parser
//! cases in `names.rs` are authored from the grammar written in plan-03 §8
//! rather than copied out of this dump: the golden file proves the two crates
//! agree today, and the hand-written cases are what notice when one of them
//! moves.

use std::path::{Path, PathBuf};

use reachgraph_plugin_api::{
    DocFormat, NodeId, PluginId, SourceRange, Span, Symbol, SymbolIndex, SymbolKind,
};
use reachgraph_roots_proto_tonic::bind::{bind_handler, Binding, Operation};

use crate::fake::FakeIndex;

const LANG_RUST: PluginId = PluginId("reachgraph-lang-rust");

fn golden() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/golden/fx-impl-symbols.tsv")
}

/// Read the dump back into `Symbol`s.
///
/// Seven fields, tab separated, `-` for an absent container. Anything else is a
/// malformed line and panics rather than being skipped: a golden file that
/// silently loses rows would weaken the very assertion it exists to make.
fn load() -> FakeIndex {
    let text = std::fs::read_to_string(golden()).expect("the golden dump is checked in");
    let mut symbols = Vec::new();
    for line in text.lines() {
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        assert_eq!(fields.len(), 7, "malformed golden row: {line:?}");

        let container = match fields[6] {
            "-" => None,
            raw => Some(NodeId {
                plugin: LANG_RUST,
                raw: raw.to_owned(),
            }),
        };
        symbols.push(Symbol {
            id: NodeId {
                plugin: LANG_RUST,
                raw: fields[0].to_owned(),
            },
            name: fields[1].to_owned(),
            kind: kind_of(fields[2]),
            raw_kind: fields[3].to_owned(),
            range: SourceRange {
                file: PathBuf::from(fields[5]),
                span: Some(Span { start: 0, end: 1 }),
            },
            doc: None,
            doc_format: DocFormat::Markdown,
            container,
            is_test: fields[4] == "true",
        });
    }
    assert!(symbols.len() > 5, "the dump has rows: {}", symbols.len());
    FakeIndex::new(symbols)
}

fn kind_of(term: &str) -> SymbolKind {
    match term {
        "Function" => SymbolKind::Function,
        "Method" => SymbolKind::Method,
        "Type" => SymbolKind::Type,
        "Module" => SymbolKind::Module,
        "Field" => SymbolKind::Field,
        "Other" => SymbolKind::Other,
        other => panic!("the dump carries a kind this test does not know: {other:?}"),
    }
}

/// `fx-impl` is shaped like a served contract: a trait `Svc` with one operation
/// `create`, a real implementation in `src/`, and a test double in `tests/`.
#[test]
fn binds_against_lang_rust_golden_symbols() {
    let index = load();
    let operation = Operation::new(Some("acme.api.v1"), "Svc", "Create");

    let binding = bind_handler(&index, &operation);
    let Binding::Bound(node) = &binding else {
        panic!("the handler in `impl Svc for Real` binds: {binding:?}");
    };

    let bound = index.get(node).expect("the bound id is in the dump");
    assert_eq!(bound.name, "create");
    assert_eq!(
        bound.range.file,
        Path::new("i/src/lib.rs"),
        "the real implementation, not the test double"
    );
}

/// The same dump, read for the fact that makes the binding non-trivial.
///
/// Three symbols in `fx-impl` are named `create`: the trait's own declaration,
/// the real implementation's, and the test double's. If a future change to
/// `reachgraph-lang-rust` stopped emitting one of them, the test above would
/// keep passing while asserting much less — so the collision is asserted
/// directly.
#[test]
fn the_golden_dump_still_contains_the_collision() {
    let index = load();
    let candidates = index.by_name("create");
    assert_eq!(
        candidates.len(),
        3,
        "trait declaration, real impl and test double: {:#?}",
        candidates
            .iter()
            .map(|symbol| (symbol.raw_kind.as_str(), symbol.range.file.display()))
            .collect::<Vec<_>>()
    );

    assert!(
        candidates
            .iter()
            .any(|symbol| symbol.range.file == Path::new("i/tests/mock.rs")),
        "the test double is in the dump, and is what the guard has to reject"
    );
    assert!(
        candidates.iter().all(|symbol| !symbol.is_test),
        "MEASURED: none of the three carries `is_test`, the mock's included — which is why \
         `is_test` alone cannot separate them"
    );
}
