//! The cross-plugin golden dump behind `cargo xtask golden-symbols`.
//!
//! Plan-04 §12's last test binds against **checked-in data** rather than
//! against a build dependency, which is the only mechanism that couples plan-03
//! and plan-04 without fusing them. This renders that data.
//!
//! # Why regeneration is a command and not a test
//!
//! Plan-04 §12 states the guard: a golden file regenerated from a test run
//! updates both sides of the contract at once, so the test then passes through
//! a break. Writing happens under `--bless` only, and the diff is meant to be
//! read — a changed line here is `reachgraph-lang-rust` changing the grammar
//! `reachgraph-roots-proto-tonic` parses.
//!
//! # Why it lives in xtask
//!
//! `reachgraph-roots-proto-tonic` must not depend on `reachgraph-lang-rust`,
//! not even for tests: that would put an `ra_ap` workspace load on the path of
//! a suite plan-04 §12 keeps to milliseconds. xtask already exists to hold
//! deliberate commands and is a dependency of nothing shipped.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use reachgraph_lang_rust::RustPlugin;
use reachgraph_plugin_api::{LanguagePlugin, Symbol, SymbolProvider};

/// The fixture that is dumped, and the file the dump is checked in as.
#[derive(Clone, Debug)]
pub struct GoldenTarget {
    /// The Cargo workspace to index.
    pub fixture: PathBuf,
    /// Where the rendering is checked in.
    pub golden: PathBuf,
}

impl GoldenTarget {
    /// `fx-impl` — a trait, its real implementation, an inherent impl, and a
    /// test double of the same trait in a `tests/` target.
    pub fn fx_impl(workspace_root: &Path) -> Self {
        Self {
            fixture: workspace_root.join("reachgraph-lang-rust/tests/fixtures/fx-impl"),
            golden: workspace_root
                .join("reachgraph-roots-proto-tonic/tests/golden/fx-impl-symbols.tsv"),
        }
    }
}

/// Render one fixture's symbols in the checked-in format.
///
/// Tab-separated rather than JSON so the file stays reviewable and the reading
/// side needs no serde: plugin-api's types cannot derive `Deserialize` at all
/// (ADR-0727), so a JSON dump would need a mirror type on both sides of a file
/// whose whole purpose is to be read by eye.
///
/// # The absolute path in a unit id is replaced
///
/// MEASURED: a `UnitId` is spelled `<package>@<version> <absolute crate dir>::…`,
/// so a verbatim dump would carry this machine's home directory and could never
/// match on another. The workspace root is written as `{workspace}`, which keeps
/// every `container` reference internally consistent — the only property the
/// reading side uses — without pinning the file to one checkout.
pub fn render(target: &GoldenTarget, workspace_root: &Path) -> Result<String, String> {
    let plugin = RustPlugin::new();
    let units = plugin
        .discover_units(&target.fixture)
        .map_err(|error| format!("{} did not load: {error}", target.fixture.display()))?;

    let mut symbols: Vec<Symbol> = Vec::new();
    for unit in &units {
        symbols.extend(
            plugin
                .symbols_in(unit)
                .map_err(|error| format!("symbols_in({}) failed: {error}", unit.id.0))?,
        );
    }
    symbols.sort_by(|left, right| left.id.raw.cmp(&right.id.raw));

    let mut out = String::new();
    out.push_str(
        "# GENERATED by `cargo xtask golden-symbols --bless`. Do not edit.\n\
         #\n\
         # `reachgraph-lang-rust`'s own output for its `fx-impl` fixture, which is the\n\
         # cross-plugin contract plan-04 §7 parses: the impl-header grammar, the\n\
         # `container` relation, `is_test`, and the path spelling. A diff here is that\n\
         # contract moving, and `binds_against_lang_rust_golden_symbols` is what notices.\n\
         #\n\
         # id\tname\tkind\traw_kind\tis_test\tfile\tcontainer\n",
    );
    let root = workspace_root.display().to_string();
    for symbol in &symbols {
        let container = symbol
            .container
            .as_ref()
            .map_or("-", |container| container.raw.as_str());
        writeln!(
            out,
            "{}\t{}\t{:?}\t{}\t{}\t{}\t{}",
            normalise(&symbol.id.raw, &root),
            symbol.name,
            symbol.kind,
            symbol.raw_kind,
            symbol.is_test,
            symbol.range.file.display(),
            normalise(container, &root)
        )
        .map_err(|error| error.to_string())?;
    }
    Ok(out)
}

/// Replace this checkout's path with a placeholder.
fn normalise(raw: &str, workspace_root: &str) -> String {
    raw.replace(workspace_root, "{workspace}")
}
